window.runningEntries = [
  {
    id: "2026-qiandaohu-full",
    type: { zh: "全程马拉松", en: "Marathon" },
    title: { zh: "2026千岛湖马拉松", en: "2026 Qiandao Lake Marathon" },
    date: { zh: "2026.11.29", en: "2026.11.29" },
    distanceKm: 42.195,
    distanceText: { zh: "42.195 km", en: "42.195 km" },
    location: { zh: "浙江省/杭州市/淳安县", en: "Zhejiang / Hangzhou / Chun'an" },
    result: { zh: "计划中", en: "planned" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "planned",
  },
  {
    id: "2026-xiangyang-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026襄阳马拉松", en: "2026 Xiangyang Marathon" },
    date: { zh: "2026.10.25", en: "2026.10.25" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "湖北省/襄阳市/樊城区", en: "Hubei / Xiangyang / Fancheng" },
    result: { zh: "计划中", en: "planned" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "planned",
  },
  {
    id: "2026-tianjin-tuanbolake-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026天津团泊湖半程马拉松", en: "2026 Tianjin Tuanbo Lake Half Marathon" },
    date: { zh: "2026.9.27", en: "2026.9.27" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "天津市/静海区", en: "Tianjin / Jinghai" },
    result: { zh: "计划中", en: "planned" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "planned",
  },
  {
    id :"2026-huhehaote-full",
    type: { zh: "全程马拉松", en: "Marathon" },
    title: { zh: "2026呼和浩特马拉松", en: "2026 Hohhot Marathon" },
    date: { zh: "2026.9.19", en: "2026.9.19" },
    distanceKm: 42.195,
    distanceText: { zh: "42.195 km", en: "42.195 km" },
    location: { zh: "内蒙古自治区/呼和浩特市/赛罕区", en: "Inner Mongolia / Hohhot / Saihan" },
    result: { zh: "计划中", en: "planned" },
    note: { zh: "中国田协C类赛事", en: "Chinese Athletics Association C-level Race" },
    status: "planned",
  },
  {
    id: "2026-chuxiong-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026楚雄马拉松", en: "2026 Chuxiong Marathon" },
    date: { zh: "2026.8.2", en: "2026.8.2" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "云南省/楚雄彝族自治州/楚雄市", en: "Yunnan / Chuxiong Yi Autonomous Prefecture / Chuxiong" },
    result: { zh: "枪时2:05:41，净时2:02:08", en: "gun time 2:05:41, net time 2:02:08" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "finished",
  },
  {
    id: "2026-linze-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026临泽马拉松", en: "2026 Linze Marathon" },
    date: { zh: "2026.6.28", en: "2026.6.28" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "甘肃省/张掖市/临泽县", en: "Gansu / Zhangye / Linze" },
    result: { zh: "DNS", en: "DNS" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "dns",
  },
  {
    id: "2026-jilin-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026吉林市马拉松", en: "2026 Jilin Marathon" },
    date: { zh: "2026.5.31", en: "2026.5.31" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "吉林省/吉林市/船营区", en: "Jilin / Jilin / Chuanying" },
    result: { zh: "枪时2:01:48，净时1:57:21", en: "gun time 2:01:48, net time 1:57:21" },
    note: { zh: "世界田联精英标牌赛事，中国田协A类赛事", en: "World Athletics Elite Label Race, Chinese Athletics Association A-level Race" },
    status: "finished",
  },
  {
    id: "2026-yicheng-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026宜城半程马拉松", en: "2026 Yicheng Half Marathon" },
    date: "2026.4.26",
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "湖北省/襄阳市/宜城市", en: "Hubei / Xiangyang / Yicheng" },
    result: { zh: "枪时1:52:06，净时1:50:47", en: "gun time 1:52:06, net time 1:50:47" },
    note: { zh: "中国田协A类赛事，PB", en: "Chinese Athletics Association A-level Race, PB" },
    status: "finished",
  },
  {
    id: "2026-great-wall-trail",
    type: { zh: "越野赛", en: "Trail Race" },
    title: {
      zh: "2026北京延庆1015八达岭石峡关谷环长城越野赛 20km八达岭守备",
      en: "2026 Great Wall Ultra Trail Badaling, 20km Shoubei",
    },
    date: "2026.4.19",
    distanceKm: 20.8,
    distanceText: { zh: "20.8 km, 1138m+", en: "20.8 km, 1138m+" },
    location: { zh: "北京市/延庆区", en: "Beijing / Yanqing" },
    result: { zh: "枪时4:29:34，净时4:29:09", en: "gun time 4:29:34, net time 4:29:09" },
    note: { zh: "ITRA 1", en: "ITRA 1" },
    status: "finished",
  },
  {
    id: "2026-xiahuayuan-trail",
    type: { zh: "越野赛", en: "Trail Race" },
    title: {
      zh: "2026第四届下花园超级越野赛 沐春晖10公里",
      en: "2026 Xiahuayuan Ultra Trail, 10km Muchunhui",
    },
    date: "2026.4.12",
    distanceKm: 13.1,
    distanceText: { zh: "13.1 km, 436m+", en: "13.1 km, 436m+" },
    location: { zh: "河北省/张家口市/下花园区", en: "Hebei / Zhangjiakou / Xiahuayuan" },
    result: { zh: "枪时1:36:38，净时1:35:01", en: "gun time 1:36:38, net time 1:35:01" },
    note: { zh: "完赛", en: "Finished" },
    status: "finished",
  },
  {
    id: "2026-nanning-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2026南宁半程马拉松", en: "2026 Nanning Half Marathon" },
    date: "2026.3.22",
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975km", en: "21.0975km" },
    location: { zh: "广西壮族自治区/南宁市/良庆区", en: "Guangxi / Nanning / Liangqing" },
    result: { zh: "枪时2:00:34，净时1:57:33", en: "gun time 2:00:34, net time 1:57:33" },
    note: { zh: "中国田协C类赛事，首半马，PB", en: "Chinese Athletics Association C-level Race, First half marathon, PB" },
    status: "finished",
  },
  {
    id: "2026-beijing-spring",
    type: { zh: "10公里", en: "10km" },
    title: { zh: "2026北京春季长跑节", en: "2026 Beijing Spring Running Festival" },
    date: "2026.3.8",
    distanceKm: 10,
    distanceText: { zh: "10 km", en: "10 km" },
    location: { zh: "北京市/大兴区", en: "Beijing / Daxing" },
    result: { zh: "枪时55:54，净时55:07", en: "gun time 55:54, net time 55:07" },
    note: { zh: "PB", en: "PB" },
    status: "finished",
  },
  {
    id: "2025-TianmuLake-half",
    type: { zh: "半程马拉松", en: "Half Marathon" },
    title: { zh: "2025天目湖马拉松", en: "2025 Tianmu Lake Marathon" },
    date: { zh: "2025.11.15", en: "2025.11.15" },
    distanceKm: 21.0975,
    distanceText: { zh: "21.0975 km", en: "21.0975 km" },
    location: { zh: "江苏省/常州市/溧阳市", en: "Jiangsu / Changzhou / Liyang" },
    result: { zh: "DNS", en: "DNS" },
    note: { zh: "中国田协A类赛事", en: "Chinese Athletics Association A-level Race" },
    status: "dns",
  },
];
